// <auto-generated />
namespace Andriy.Mvc4Application1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ParentCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ParentCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201309142104582_ParentCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
