// <auto-generated />
namespace Andriy.Mvc4Application1.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class ShopProductCategory2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShopProductCategory2));
        
        string IMigrationMetadata.Id
        {
            get { return "201307071825201_ShopProductCategory2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
